# Generated by Django 4.2.6 on 2023-12-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('speciality', models.CharField(max_length=255)),
                ('teacher_name', models.CharField(max_length=50)),
                ('teacher_surname', models.CharField(max_length=50)),
                ('grade', models.PositiveIntegerField()),
            ],
        ),
    ]
